### ISSUE TITLE
No have addons information on listUserPurchases

### ISSUE THREAD

**Issue by hugolompto** [everyday-as/gmodstore-javascript-sdk#3]
Hello,
I want to get all buy of someone but, when I do this code : 

```js
let apiInstance = new GmodstoreSdk.UserPurchasesApi();
let userId = 'steamid64'; // Number | Id of the user
let opts = {
  '_with': ["null"] // [String] | The relations you want to fetch with the `AddonPurchase`
};
apiInstance.listUserPurchases(userId, opts, (error, data, response) => {
  if (error) {
    console.error(error);
  } else {
    console.log(data);
  }
});
```
It return me 
![image](https://user-images.githubusercontent.com/51268820/96519749-fa007000-126d-11eb-8d3e-d80b66d1703b.png) 
and I don't have addons informations ( https://github.com/everyday-as/gmodstore-javascript-sdk/blob/master/docs/AddonPurchase.md )

My token permissions is : ![image](https://cdn.discordapp.com/attachments/605080919295918081/767881696049102898/unknown.png)

Thanks for helping me

**Comment by Marcuzz** [comment]
Hi,

You need to set the following:

```js
let opts = {
  '_with': ["addon"]
};
```

You can find the available with parameters here: https://docs.gmodstore.com/#operation/listUserPurchases

**Comment by hugolompto** [comment]
Hi,
It's work, thanks you very much
Have a nice day
